package raw

import "strings"

// grafanaSetupGuide returns actionable setup instructions shown when a
// `raw grafana …` command runs without a Grafana service account token. The
// embedded Grafana is session-gated and only accepts a glsa_ token generated by
// groundcover's official CLI, which shares the "groundcover" binary name with
// this CLI, so the guide steers around that PATH collision.
func grafanaSetupGuide() string {
	return strings.TrimSpace(`
missing Grafana service account token (required for raw grafana commands)

The embedded Grafana at app.groundcover.com/grafana is session-gated and does not
accept your gcsa API key. It needs a Grafana service account token (glsa_...).

Already have one? Set it and re-run:
  export GROUNDCOVER_GRAFANA_SERVICE_ACCOUNT_TOKEN=glsa_...
  # or pass --grafana-token glsa_...

To generate one (requires a groundcover tenant admin):
  1. Install groundcover's official CLI. It installs to ~/.groundcover/bin and does
     not delete this CLI, but it prepends that dir to your PATH (see note below):
       sh -c "$(curl -fsSL https://groundcover.com/install.sh)"
  2. Authenticate:
       ~/.groundcover/bin/groundcover auth login
  3. Generate the token (shown only once, so copy it):
       ~/.groundcover/bin/groundcover auth generate-service-account-token
  4. Hand it to this CLI:
       export GROUNDCOVER_GRAFANA_SERVICE_ACCOUNT_TOKEN=glsa_...

Note: groundcover's official CLI shares the "groundcover" binary name with this one.
Its installer prepends ~/.groundcover/bin to your PATH, so a new shell's "groundcover"
will resolve to the official CLI. Invoke the official one by full path (as above), or
remove that PATH line from your shell rc to keep this CLI as "groundcover".

Docs: https://docs.groundcover.com/use-groundcover/remote-access-and-apis/build-alerts-and-dashboards-with-grafana-terraform-provider
`)
}
