package raw

var ExtraCommands = []Command{
	{
		Name:         []string{"grafana", "search"},
		Method:       "GET",
		Path:         "/grafana/api/search",
		Description:  "GET /grafana/api/search",
		DefaultQuery: map[string]string{"limit": "50", "page": "1", "type": "dash-db"},
		WebApp:       true,
	},
	{
		Name:        []string{"grafana", "search", "sorting"},
		Method:      "GET",
		Path:        "/grafana/api/search/sorting",
		Description: "GET /grafana/api/search/sorting",
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "dashboards", "save"},
		Method:      "POST",
		Path:        "/grafana/api/dashboards/db",
		Description: "POST /grafana/api/dashboards/db",
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "dashboards", "get"},
		Method:      "GET",
		Path:        "/grafana/api/dashboards/uid/:dashboardUid",
		Description: "GET /grafana/api/dashboards/uid/:dashboardUid",
		PathParams:  []string{"dashboardUid"},
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "dashboards", "delete"},
		Method:      "DELETE",
		Path:        "/grafana/api/dashboards/uid/:dashboardUid",
		Description: "DELETE /grafana/api/dashboards/uid/:dashboardUid",
		PathParams:  []string{"dashboardUid"},
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "dashboards", "permissions", "get"},
		Method:      "GET",
		Path:        "/grafana/api/dashboards/uid/:dashboardUid/permissions",
		Description: "GET /grafana/api/dashboards/uid/:dashboardUid/permissions",
		PathParams:  []string{"dashboardUid"},
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "dashboards", "permissions", "update"},
		Method:      "POST",
		Path:        "/grafana/api/dashboards/uid/:dashboardUid/permissions",
		Description: "POST /grafana/api/dashboards/uid/:dashboardUid/permissions",
		PathParams:  []string{"dashboardUid"},
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "dashboards", "versions"},
		Method:      "GET",
		Path:        "/grafana/api/dashboards/id/:dashboardId/versions",
		Description: "GET /grafana/api/dashboards/id/:dashboardId/versions",
		PathParams:  []string{"dashboardId"},
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "dashboards", "versions", "get"},
		Method:      "GET",
		Path:        "/grafana/api/dashboards/id/:dashboardId/versions/:version",
		Description: "GET /grafana/api/dashboards/id/:dashboardId/versions/:version",
		PathParams:  []string{"dashboardId", "version"},
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "dashboards", "versions", "restore"},
		Method:      "POST",
		Path:        "/grafana/api/dashboards/id/:dashboardId/restore",
		Description: "POST /grafana/api/dashboards/id/:dashboardId/restore",
		PathParams:  []string{"dashboardId"},
		WebApp:      true,
	},
	{
		Name:         []string{"grafana", "folders", "list"},
		Method:       "GET",
		Path:         "/grafana/api/folders",
		Description:  "GET /grafana/api/folders",
		DefaultQuery: map[string]string{"limit": "50", "page": "1"},
		WebApp:       true,
	},
	{
		Name:        []string{"grafana", "folders", "get"},
		Method:      "GET",
		Path:        "/grafana/api/folders/:folderUid",
		Description: "GET /grafana/api/folders/:folderUid",
		PathParams:  []string{"folderUid"},
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "folders", "create"},
		Method:      "POST",
		Path:        "/grafana/api/folders",
		Description: "POST /grafana/api/folders",
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "folders", "update"},
		Method:      "PUT",
		Path:        "/grafana/api/folders/:folderUid",
		Description: "PUT /grafana/api/folders/:folderUid",
		PathParams:  []string{"folderUid"},
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "folders", "delete"},
		Method:      "DELETE",
		Path:        "/grafana/api/folders/:folderUid",
		Description: "DELETE /grafana/api/folders/:folderUid",
		PathParams:  []string{"folderUid"},
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "folders", "permissions", "get"},
		Method:      "GET",
		Path:        "/grafana/api/folders/:folderUid/permissions",
		Description: "GET /grafana/api/folders/:folderUid/permissions",
		PathParams:  []string{"folderUid"},
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "folders", "permissions", "update"},
		Method:      "POST",
		Path:        "/grafana/api/folders/:folderUid/permissions",
		Description: "POST /grafana/api/folders/:folderUid/permissions",
		PathParams:  []string{"folderUid"},
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "prometheus", "rules"},
		Method:      "GET",
		Path:        "/grafana/api/prometheus/grafana/api/v1/rules",
		Description: "GET /grafana/api/prometheus/grafana/api/v1/rules",
		WebApp:      true,
	},
	{
		Name:         []string{"grafana", "annotations", "list"},
		Method:       "GET",
		Path:         "/grafana/api/annotations",
		Description:  "GET /grafana/api/annotations",
		DefaultQuery: map[string]string{"limit": "100", "matchAny": "false"},
		WebApp:       true,
	},
	{
		Name:        []string{"grafana", "annotations", "create"},
		Method:      "POST",
		Path:        "/grafana/api/annotations",
		Description: "POST /grafana/api/annotations",
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "annotations", "update"},
		Method:      "PUT",
		Path:        "/grafana/api/annotations/:annotationId",
		Description: "PUT /grafana/api/annotations/:annotationId",
		PathParams:  []string{"annotationId"},
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "annotations", "delete"},
		Method:      "DELETE",
		Path:        "/grafana/api/annotations/:annotationId",
		Description: "DELETE /grafana/api/annotations/:annotationId",
		PathParams:  []string{"annotationId"},
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "datasources", "label-values"},
		Method:      "GET",
		Path:        "/grafana/api/datasources/uid/:datasourceUid/resources/api/v1/label/:label/values",
		Description: "GET /grafana/api/datasources/uid/:datasourceUid/resources/api/v1/label/:label/values",
		PathParams:  []string{"datasourceUid", "label"},
		WebApp:      true,
	},
	{
		Name:        []string{"grafana", "ds", "query"},
		Method:      "POST",
		Path:        "/grafana/api/ds/query",
		Description: "POST /grafana/api/ds/query",
		WebApp:      true,
	},
}
